In [1]:
import cv2
import pandas as pd
import numpy as np
import os
import joblib
from sklearn.cluster import KMeans
from sklearn.model_selection import train_test_split
import matplotlib.pyplot as plt
from sklearn.tree import DecisionTreeClassifier
from sklearn import preprocessing
from skimage.filters import sobel
from skimage.feature import graycomatrix, graycoprops
from skimage.measure import shannon_entropy
import warnings
warnings.filterwarnings('ignore')
#Importing Required Libraries
import numpy as np
import pandas as pd
import os
import csv
import cv2
import matplotlib.pyplot as plt
from sklearn.cluster import KMeans
from sklearn.model_selection import train_test_split
from sklearn import svm, datasets
from sklearn.metrics import classification_report
from sklearn.tree import DecisionTreeClassifier
import sklearn.metrics as metrics
from sklearn.metrics import accuracy_score
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC
from sklearn.model_selection import cross_val_score
from sklearn.metrics import accuracy_score,f1_score, classification_report, confusion_matrix , accuracy_score, precision_score, recall_score, f1_score, roc_curve ,roc_auc_score,ConfusionMatrixDisplay
from xgboost import XGBClassifier
from sklearn.neighbors import KNeighborsClassifier

In [3]:
#Path of dataset
Eating="C:/Users/Aditya/Downloads/CVCP/CV_DATASET/Eating_Images"
Walking="C:/Users/Aditya/Downloads/CVCP/CV_DATASET/Walking Images"
ChitChat="C:/Users/Aditya/Downloads/CVCP/CV_DATASET/Chit chat"

In [4]:
i=0
for filename in os.listdir(Eating):
    img = cv2.imread(os.path.join(Eating, filename))
    if img is not None:
        resize=(256,256)
        img=cv2.resize(img,resize)
        #grayscaling the image dataset
        gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
        img2 = cv2.GaussianBlur(gray, (5, 5), 0)  # gaussian Image

        # creating a Histograms Equalization for folder1(Fall)
        equ = cv2.equalizeHist(img2)

        # cv2.imshow('Chain Snatching Detection', equ)

        #Applyed
       
        kernelx = np.array([[1,1,1],[0,0,0],[-1,-1,-1]]) #kernels for prewitt edge detection
        kernely = np.array([[-1,0,1],[-1,0,1],[-1,0,1]])
        img_prewittx = cv2.filter2D(equ, -1, kernelx)#Horizontal 
        img_prewitty = cv2.filter2D(equ, -1, kernely)#Vertical
        img_prewitt = img_prewittx + img_prewitty

        orb = cv2.ORB_create(nfeatures=1000)
        keypoints = orb.detect(img_prewitt,None)
        keypoints, descriptors = orb.compute(img_prewitt, keypoints)
        #convert the descriptor array into a dataframe format
        out = pd.DataFrame(descriptors)
        print("descriptor shape ", i, " : ", out.shape)
        i = i + 1

        csv_data = out.to_csv('ORBEating.csv', mode='a', header=False, index=False)

descriptor shape  0  :  (889, 32)
descriptor shape  1  :  (867, 32)
descriptor shape  2  :  (785, 32)
descriptor shape  3  :  (790, 32)
descriptor shape  4  :  (830, 32)
descriptor shape  5  :  (873, 32)
descriptor shape  6  :  (833, 32)
descriptor shape  7  :  (761, 32)
descriptor shape  8  :  (832, 32)
descriptor shape  9  :  (869, 32)
descriptor shape  10  :  (855, 32)
descriptor shape  11  :  (869, 32)
descriptor shape  12  :  (854, 32)
descriptor shape  13  :  (846, 32)
descriptor shape  14  :  (877, 32)
descriptor shape  15  :  (778, 32)
descriptor shape  16  :  (851, 32)
descriptor shape  17  :  (846, 32)
descriptor shape  18  :  (835, 32)
descriptor shape  19  :  (861, 32)
descriptor shape  20  :  (869, 32)
descriptor shape  21  :  (861, 32)
descriptor shape  22  :  (812, 32)
descriptor shape  23  :  (905, 32)
descriptor shape  24  :  (876, 32)
descriptor shape  25  :  (793, 32)
descriptor shape  26  :  (829, 32)
descriptor shape  27  :  (875, 32)
descriptor shape  28  :  (858,

descriptor shape  233  :  (880, 32)
descriptor shape  234  :  (859, 32)
descriptor shape  235  :  (768, 32)
descriptor shape  236  :  (852, 32)
descriptor shape  237  :  (817, 32)
descriptor shape  238  :  (788, 32)
descriptor shape  239  :  (870, 32)
descriptor shape  240  :  (879, 32)
descriptor shape  241  :  (839, 32)
descriptor shape  242  :  (782, 32)
descriptor shape  243  :  (876, 32)
descriptor shape  244  :  (866, 32)
descriptor shape  245  :  (845, 32)
descriptor shape  246  :  (830, 32)
descriptor shape  247  :  (867, 32)
descriptor shape  248  :  (828, 32)
descriptor shape  249  :  (876, 32)
descriptor shape  250  :  (879, 32)
descriptor shape  251  :  (845, 32)
descriptor shape  252  :  (883, 32)
descriptor shape  253  :  (862, 32)
descriptor shape  254  :  (867, 32)
descriptor shape  255  :  (746, 32)
descriptor shape  256  :  (833, 32)
descriptor shape  257  :  (802, 32)
descriptor shape  258  :  (820, 32)
descriptor shape  259  :  (897, 32)
descriptor shape  260  :  (8

In [5]:
i=0
for filename in os.listdir(Walking):
    img = cv2.imread(os.path.join(Walking, filename))
    if img is not None:
        resize=(256,256)
        img=cv2.resize(img,resize)
        #grayscaling the image dataset
        gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
        img2 = cv2.GaussianBlur(gray, (5, 5), 0)  # gaussian Image

        # creating a Histograms Equalization for folder1(Fall)
        equ = cv2.equalizeHist(img2)

        # cv2.imshow('Chain Snatching Detection', equ)

        #Applyed
        
        kernelx = np.array([[1,1,1],[0,0,0],[-1,-1,-1]]) #kernels for prewitt edge detection
        kernely = np.array([[-1,0,1],[-1,0,1],[-1,0,1]])
        img_prewittx = cv2.filter2D(equ, -1, kernelx)#Horizontal 
        img_prewitty = cv2.filter2D(equ, -1, kernely)#Vertical
        img_prewitt = img_prewittx + img_prewitty

        orb = cv2.ORB_create(nfeatures=1000)
        keypoints = orb.detect(img_prewitt,None)
        keypoints, descriptors = orb.compute(img_prewitt, keypoints)

        #convert the descriptor array into a dataframe format
        out = pd.DataFrame(descriptors)
        print("descriptor shape ", i, " : ", out.shape)
        i = i + 1

        csv_data = out.to_csv('ORBWalking.csv', mode='a', header=False, index=False)

descriptor shape  0  :  (306, 32)
descriptor shape  1  :  (194, 32)
descriptor shape  2  :  (460, 32)
descriptor shape  3  :  (825, 32)
descriptor shape  4  :  (283, 32)
descriptor shape  5  :  (186, 32)
descriptor shape  6  :  (713, 32)
descriptor shape  7  :  (389, 32)
descriptor shape  8  :  (344, 32)
descriptor shape  9  :  (496, 32)
descriptor shape  10  :  (918, 32)
descriptor shape  11  :  (904, 32)
descriptor shape  12  :  (884, 32)
descriptor shape  13  :  (609, 32)
descriptor shape  14  :  (878, 32)
descriptor shape  15  :  (844, 32)
descriptor shape  16  :  (394, 32)
descriptor shape  17  :  (865, 32)
descriptor shape  18  :  (291, 32)
descriptor shape  19  :  (434, 32)
descriptor shape  20  :  (450, 32)
descriptor shape  21  :  (252, 32)
descriptor shape  22  :  (628, 32)
descriptor shape  23  :  (885, 32)
descriptor shape  24  :  (869, 32)
descriptor shape  25  :  (869, 32)
descriptor shape  26  :  (817, 32)
descriptor shape  27  :  (837, 32)
descriptor shape  28  :  (792,

descriptor shape  236  :  (760, 32)
descriptor shape  237  :  (557, 32)
descriptor shape  238  :  (849, 32)
descriptor shape  239  :  (861, 32)
descriptor shape  240  :  (729, 32)
descriptor shape  241  :  (431, 32)
descriptor shape  242  :  (585, 32)
descriptor shape  243  :  (668, 32)
descriptor shape  244  :  (782, 32)
descriptor shape  245  :  (842, 32)
descriptor shape  246  :  (819, 32)
descriptor shape  247  :  (851, 32)
descriptor shape  248  :  (867, 32)
descriptor shape  249  :  (844, 32)
descriptor shape  250  :  (866, 32)
descriptor shape  251  :  (874, 32)
descriptor shape  252  :  (256, 32)
descriptor shape  253  :  (504, 32)
descriptor shape  254  :  (631, 32)
descriptor shape  255  :  (802, 32)
descriptor shape  256  :  (771, 32)
descriptor shape  257  :  (738, 32)
descriptor shape  258  :  (884, 32)
descriptor shape  259  :  (786, 32)
descriptor shape  260  :  (798, 32)
descriptor shape  261  :  (390, 32)
descriptor shape  262  :  (701, 32)
descriptor shape  263  :  (7

In [6]:
i=0
for filename in os.listdir(ChitChat):
    img = cv2.imread(os.path.join(ChitChat, filename))
    if img is not None:
        resize=(256,256)
        img=cv2.resize(img,resize)
        #grayscaling the image dataset
        gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
        img2 = cv2.GaussianBlur(gray, (5, 5), 0)  # gaussian Image

        # creating a Histograms Equalization for folder1(Fall)
        equ = cv2.equalizeHist(img2)

        # cv2.imshow('Chain Snatching Detection', equ)

        #Applyed
        kernelx = np.array([[1,1,1],[0,0,0],[-1,-1,-1]]) #kernels for prewitt edge detection
        kernely = np.array([[-1,0,1],[-1,0,1],[-1,0,1]])
        img_prewittx = cv2.filter2D(equ, -1, kernelx)#Horizontal 
        img_prewitty = cv2.filter2D(equ, -1, kernely)#Vertical
        img_prewitt = img_prewittx + img_prewitty

        orb = cv2.ORB_create(nfeatures=1000)
        keypoints = orb.detect(img_prewitt,None)
        keypoints, descriptors = orb.compute(img_prewitt, keypoints)


        #convert the descriptor array into a dataframe format
        out = pd.DataFrame(descriptors)
        print("descriptor shape ", i, " : ", out.shape)
        i = i + 1

        csv_data = out.to_csv('ORBChitChat.csv', mode='a', header=False, index=False)

descriptor shape  0  :  (859, 32)
descriptor shape  1  :  (870, 32)
descriptor shape  2  :  (885, 32)
descriptor shape  3  :  (803, 32)
descriptor shape  4  :  (904, 32)
descriptor shape  5  :  (833, 32)
descriptor shape  6  :  (775, 32)
descriptor shape  7  :  (856, 32)
descriptor shape  8  :  (887, 32)
descriptor shape  9  :  (839, 32)
descriptor shape  10  :  (875, 32)
descriptor shape  11  :  (805, 32)
descriptor shape  12  :  (898, 32)
descriptor shape  13  :  (820, 32)
descriptor shape  14  :  (827, 32)
descriptor shape  15  :  (829, 32)
descriptor shape  16  :  (883, 32)
descriptor shape  17  :  (882, 32)
descriptor shape  18  :  (876, 32)
descriptor shape  19  :  (894, 32)
descriptor shape  20  :  (859, 32)
descriptor shape  21  :  (882, 32)
descriptor shape  22  :  (892, 32)
descriptor shape  23  :  (881, 32)
descriptor shape  24  :  (819, 32)
descriptor shape  25  :  (890, 32)
descriptor shape  26  :  (907, 32)
descriptor shape  27  :  (879, 32)
descriptor shape  28  :  (845,

descriptor shape  232  :  (817, 32)
descriptor shape  233  :  (745, 32)
descriptor shape  234  :  (893, 32)
descriptor shape  235  :  (672, 32)
descriptor shape  236  :  (637, 32)
descriptor shape  237  :  (705, 32)
descriptor shape  238  :  (771, 32)
descriptor shape  239  :  (785, 32)
descriptor shape  240  :  (800, 32)
descriptor shape  241  :  (799, 32)
descriptor shape  242  :  (819, 32)
descriptor shape  243  :  (811, 32)
descriptor shape  244  :  (808, 32)
descriptor shape  245  :  (867, 32)
descriptor shape  246  :  (853, 32)
descriptor shape  247  :  (871, 32)
descriptor shape  248  :  (810, 32)
descriptor shape  249  :  (812, 32)
descriptor shape  250  :  (841, 32)
descriptor shape  251  :  (862, 32)
descriptor shape  252  :  (767, 32)
descriptor shape  253  :  (826, 32)
descriptor shape  254  :  (819, 32)
descriptor shape  255  :  (836, 32)
descriptor shape  256  :  (903, 32)
descriptor shape  257  :  (774, 32)
descriptor shape  258  :  (878, 32)
descriptor shape  259  :  (8

descriptor shape  465  :  (886, 32)
descriptor shape  466  :  (907, 32)
descriptor shape  467  :  (831, 32)
descriptor shape  468  :  (755, 32)


In [7]:
data1 = pd.read_csv('ORBEating.csv', dtype='uint8',header=None)
data2 = pd.read_csv('ORBWalking.csv', dtype='uint8',header=None)
data3 = pd.read_csv('ORBChitChat.csv', dtype='uint8',header=None)

In [8]:
data1

0    1    2    3    4    5    6    7    8    9   ...   22   23   24  \
0       145  219   94  173  182  139  118  245  236  112  ...    4   61  224   
1       175  228   32   42   29  149  202  200   87  192  ...   95  151  168   
2       109  167  192   69  221   31   79  185   83  164  ...  253  158  110   
3        73   49  186   69   67   94  113   16  121  192  ...  178   64   71   
4       248  238   64   46   88  203   86  236   19  164  ...  200   63  242   
...     ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...   
351288   41  232  228   69    5   31  200  184  119  224  ...  125   61   14   
351289  244  251  156  166  154   27   22  156    3  252  ...  203   40  250   
351290   45  172  100    5   93   23  202  234   83  226  ...  125  191   62   
351291   92  191  156  165  138   11   22  191  162  174  ...  203   10  248   
351292   89  159  151   37  139  142  182  167  168  234  ...  205   12  172   

         25   26   27   28   29   30   31  
0       129  101  182  124  184  219  139  
1        92  143  124   91    7  122  148  
2       221  133  117  115  254  222  196  
3       249    5    2   74   34   67  162  
4       197    5   59  115  154    6  138  
...     ...  ...  ...  ...  ...  ...  ...  
351288   94  209   52   75  135   90  140  
351289  133   37  191   40   59  142   91  
351290   30  133   52  219  238   90  140  
351291  231  109  253  168  122  143   91  
351292  103  111  148  200  118  139   93  

[351293 rows x 32 columns]

In [9]:
data2

0    1    2    3    4    5    6    7    8    9   ...   22   23   24  \
0        80   34   26  160    8   24   16   64  232   76  ...  164    0  144   
1        55   18  239   21  162   95  252   56  124  234  ...   53   76   14   
2       114   50   40  136   42   81   17   72   33  108  ...  230    0  208   
3        90   50   43    8   11   81   16   64   34  108  ...  244   80  208   
4        19   18  247   69   67   86  109  112  117   78  ...   53  204   55   
...     ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...   
289152   34  168  135   86   76  195   68  198  243  146  ...  202   56    1   
289153  124  160   42  184  136  201   81   75  162   21  ...  226   16  219   
289154  101  117   21  224  152  111   71  152   32  248  ...  249    8  225   
289155  193    4    5  229   52   14  110   56   48  162  ...  193   14  228   
289156   90   32    1  184    9  201    8    0  166  160  ...  194  144  145   

         25   26   27   28   29   30   31  
0       225   32  153  104    8   31   85  
1        42  237  131  237  100   87  215  
2         0  170  187   60    4   39  119  
3        33  170  187   41    4   47  115  
4       106   65  130  111  164  118  212  
...     ...  ...  ...  ...  ...  ...  ...  
289152  154  213   42  192  112  114  170  
289153  193   21  127  208    0  246   66  
289154  136   37   52  160  243   66  112  
289155  174  162    0   44  162   80   32  
289156  240  139   59   48    4   19    2  

[289157 rows x 32 columns]

In [10]:
data3

0    1    2    3    4    5    6    7    8    9   ...   22   23   24  \
0       221   37  142  165  132   10   77  175  114  179  ...  141    8  232   
1        92   36  135  182  141  104   69    1  163  150  ...  250  160  209   
2       212   98  249  230   44  104   75  136   97  182  ...  235   32  209   
3       241   87   35   76   29   14  199  118  224  140  ...  241   14  177   
4       117   57  223   68    3  114   78   72   33  192  ...  145   74  147   
...     ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...   
397825   75   17  253  117   39   30  121   19   45  113  ...  241  192  199   
397826  116  166  197   15  146   43   34  136   54  161  ...  205   61   12   
397827  229  112  245   66   77   63   70  152  235  250  ...  255   32   31   
397828   48  237   56   90  221  205   87  239  195   29  ...  202   53  123   
397829   91    1  244  229   39   12  120   21   41    1  ...  145  192  215   

         25   26   27   28   29   30   31  
0       227  255   85  168  112  153    2  
1       242  215   25  162  115   52   98  
2       242   69   60  160  243   70   96  
3       248   34   24   64   42  118  108  
4       239   69    2  235  243   42  180  
...     ...  ...  ...  ...  ...  ...  ...  
397825  251   88  130  198  132  193  123  
397826   38  213   84  233  227  242    0  
397827   91   69   62  202  255   82  100  
397828  157   20  123   81   10  246  170  
397829  249   18   66  103  134  193   10  

[397830 rows x 32 columns]

In [11]:
data = pd.concat([data1, data2,data3], axis=0)

In [12]:
data

0    1    2    3    4    5    6    7    8    9   ...   22   23   24  \
0       145  219   94  173  182  139  118  245  236  112  ...    4   61  224   
1       175  228   32   42   29  149  202  200   87  192  ...   95  151  168   
2       109  167  192   69  221   31   79  185   83  164  ...  253  158  110   
3        73   49  186   69   67   94  113   16  121  192  ...  178   64   71   
4       248  238   64   46   88  203   86  236   19  164  ...  200   63  242   
...     ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...   
397825   75   17  253  117   39   30  121   19   45  113  ...  241  192  199   
397826  116  166  197   15  146   43   34  136   54  161  ...  205   61   12   
397827  229  112  245   66   77   63   70  152  235  250  ...  255   32   31   
397828   48  237   56   90  221  205   87  239  195   29  ...  202   53  123   
397829   91    1  244  229   39   12  120   21   41    1  ...  145  192  215   

         25   26   27   28   29   30   31  
0       129  101  182  124  184  219  139  
1        92  143  124   91    7  122  148  
2       221  133  117  115  254  222  196  
3       249    5    2   74   34   67  162  
4       197    5   59  115  154    6  138  
...     ...  ...  ...  ...  ...  ...  ...  
397825  251   88  130  198  132  193  123  
397826   38  213   84  233  227  242    0  
397827   91   69   62  202  255   82  100  
397828  157   20  123   81   10  246  170  
397829  249   18   66  103  134  193   10  

[1038280 rows x 32 columns]

In [13]:
#save appended data into a csv file
csv_data=data.to_csv('finalDataORB.csv', mode='a', header=False,index=False)

In [14]:
#read the data from the previously saved csv file
data = pd.read_csv('finalDataORB.csv',header=None)
data

0    1    2    3    4    5    6    7    8    9   ...   22   23   24  \
0        145  219   94  173  182  139  118  245  236  112  ...    4   61  224   
1        175  228   32   42   29  149  202  200   87  192  ...   95  151  168   
2        109  167  192   69  221   31   79  185   83  164  ...  253  158  110   
3         73   49  186   69   67   94  113   16  121  192  ...  178   64   71   
4        248  238   64   46   88  203   86  236   19  164  ...  200   63  242   
...      ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...   
1038275   75   17  253  117   39   30  121   19   45  113  ...  241  192  199   
1038276  116  166  197   15  146   43   34  136   54  161  ...  205   61   12   
1038277  229  112  245   66   77   63   70  152  235  250  ...  255   32   31   
1038278   48  237   56   90  221  205   87  239  195   29  ...  202   53  123   
1038279   91    1  244  229   39   12  120   21   41    1  ...  145  192  215   

          25   26   27   28   29   30   31  
0        129  101  182  124  184  219  139  
1         92  143  124   91    7  122  148  
2        221  133  117  115  254  222  196  
3        249    5    2   74   34   67  162  
4        197    5   59  115  154    6  138  
...      ...  ...  ...  ...  ...  ...  ...  
1038275  251   88  130  198  132  193  123  
1038276   38  213   84  233  227  242    0  
1038277   91   69   62  202  255   82  100  
1038278  157   20  123   81   10  246  170  
1038279  249   18   66  103  134  193   10  

[1038280 rows x 32 columns]

In [15]:
##    K meanse Clustring
#Applying Kmeans
kmeans = KMeans(n_clusters=3)
kmeans.fit(data)

KMeans(n_clusters=3)

In [16]:
#save the model to disk
import pickle
filename = 'Kmeans_CL_2_Model.sav'
pickle.dump(kmeans, open(filename, 'wb'))

In [17]:
#calculate histogram of trained kmeans
hist = np.histogram(kmeans.labels_,bins=[0,1,2,3])

print("Histogram of trained kmeans")
print(hist, "\n")

Histogram of trained kmeans
(array([310681, 362467, 365132], dtype=int64), array([0, 1, 2, 3])) 



In [18]:


#initialising i=0; as it is the first class
i=0
data=[]
#k=0

for filename in os.listdir(Eating):
    #path
    path=os.path.join(Eating,filename)
    a=cv2.imread(path)

    #gray image
    gray = cv2.cvtColor(a, cv2.COLOR_BGR2GRAY)

    # creating a Histograms Equalization for folder1(Fall)
    equ = cv2.equalizeHist(gray)

    #Applyeda
  
    #Applying Sift  Discriptor Abnormal folder
    kernelx = np.array([[1,1,1],[0,0,0],[-1,-1,-1]]) #kernels for prewitt edge detection
    kernely = np.array([[-1,0,1],[-1,0,1],[-1,0,1]])
    img_prewittx = cv2.filter2D(equ, -1, kernelx)#Horizontal 
    img_prewitty = cv2.filter2D(equ, -1, kernely)#Vertical
    img_prewitt = img_prewittx + img_prewitty    
    orb = cv2.ORB_create(nfeatures=1000)
    kp, descriptors = orb.detectAndCompute(img_prewitt, None)

    out=pd.DataFrame(descriptors)

    array_double = np.array(out, dtype=np.double)
    try:
        a=kmeans.predict(array_double)
    except:
        print(filename)
    hist=np.histogram(a,bins=[0,1,2,3])

    #append the dataframe into the array
    data.append(hist[0])


#convert Array to Dataframe and append to the list
Output = pd.DataFrame(data)
#add row class
Output["Class"] = i
csv_data=Output.to_csv('finalORBEating.csv', mode='a',header=False,index=False)

In [19]:
#performing kmeans prediction on the Abnormal with the pretrained kmeans model

#initialising i=0; as it is the first class
i=1
data=[]
#k=0

for filename in os.listdir(Walking):
    #path
    path=os.path.join(Walking,filename)
    a=cv2.imread(path)

    #gray image
    gray = cv2.cvtColor(a, cv2.COLOR_BGR2GRAY)

    # creating a Histograms Equalization for folder1(Fall)
    equ = cv2.equalizeHist(gray)

    #Applyeda
  
    #Applying Sift  Discriptor Abnormal folder
    kernelx = np.array([[1,1,1],[0,0,0],[-1,-1,-1]]) #kernels for prewitt edge detection
    kernely = np.array([[-1,0,1],[-1,0,1],[-1,0,1]])
    img_prewittx = cv2.filter2D(equ, -1, kernelx)#Horizontal 
    img_prewitty = cv2.filter2D(equ, -1, kernely)#Vertical
    img_prewitt = img_prewittx + img_prewitty    
    orb = cv2.ORB_create(nfeatures=1000)
    kp, descriptors = orb.detectAndCompute(img_prewitt, None)

    out=pd.DataFrame(descriptors)

    array_double = np.array(out, dtype=np.double)
    try:
        a=kmeans.predict(array_double)
    except:
        print(filename)
    hist=np.histogram(a,bins=[0,1,2,3])

    #append the dataframe into the array
    data.append(hist[0])


#convert Array to Dataframe and append to the list
Output = pd.DataFrame(data)
#add row class
Output["Class"] = i
csv_data=Output.to_csv('finalORBWalking.csv', mode='a',header=False,index=False)

In [20]:
#performing kmeans prediction on the Abnormal with the pretrained kmeans model

#initialising i=0; as it is the first class
i=2
data=[]
#k=0

for filename in os.listdir(ChitChat):
    #path
    path=os.path.join(ChitChat,filename)
    a=cv2.imread(path)

    #gray image
    gray = cv2.cvtColor(a, cv2.COLOR_BGR2GRAY)

    # creating a Histograms Equalization for folder1(Fall)
    equ = cv2.equalizeHist(gray)

    #Applyeda
  
    #Applying Sift  Discriptor Abnormal folder
    kernelx = np.array([[1,1,1],[0,0,0],[-1,-1,-1]]) #kernels for prewitt edge detection
    kernely = np.array([[-1,0,1],[-1,0,1],[-1,0,1]])
    img_prewittx = cv2.filter2D(equ, -1, kernelx)#Horizontal 
    img_prewitty = cv2.filter2D(equ, -1, kernely)#Vertical
    img_prewitt = img_prewittx + img_prewitty    
    orb = cv2.ORB_create(nfeatures=1000)
    kp, descriptors = orb.detectAndCompute(img_prewitt, None)

    out=pd.DataFrame(descriptors)

    array_double = np.array(out, dtype=np.double)
    try:
        a=kmeans.predict(array_double)
    except:
        print(filename)
    hist=np.histogram(a,bins=[0,1,2,3])

    #append the dataframe into the array
    data.append(hist[0])


#convert Array to Dataframe and append to the list
Output = pd.DataFrame(data)
#add row class
Output["Class"] = i
csv_data=Output.to_csv('finalORBChitChat.csv', mode='a',header=False,index=False)

In [21]:
#Displaying the kmeans predicted data of folder1
print("Eating")
dat1= pd.read_csv('finalORBEating.csv',header=None)
print(dat1)

Eating
       0    1    2  3
0    264  202  304  0
1    293  224  240  0
2    219  243  233  0
3    267  210  219  0
4    310  201  199  0
..   ...  ...  ... ..
412  290  214  245  0
413  235  229  275  0
414  197  204  294  0
415  233  270  252  0
416  261  210  274  0

[417 rows x 4 columns]


In [22]:
#Displaying the kmeans predicted data of folder1
print("Walking")
dat2= pd.read_csv('finalORBWalking.csv',header=None)
print(dat2)

Walking
       0    1    2  3
0    154  415  431  1
1    140  477  372  1
2    156  241  307  1
3     31  487  483  1
4    138  415  381  1
..   ...  ...  ... ..
415   78  474  448  1
416   59  533  408  1
417  106  416  372  1
418  120  193  192  1
419   70  205  212  1

[420 rows x 4 columns]


In [23]:
#Displaying the kmeans predicted data of folder1
print("Chit-Chat")
dat3= pd.read_csv('finalORBChitChat.csv',header=None)
print(dat3)

Chit-Chat
       0    1    2  3
0    244  380  376  2
1    248  362  390  2
2    241  381  378  2
3    261  353  386  2
4    234  416  350  2
..   ...  ...  ... ..
464  381  295  324  2
465  281  330  389  2
466  410  259  331  2
467  281  320  399  2
468  270  291  330  2

[469 rows x 4 columns]


In [24]:
#appending All kmeans predicted data into 1 dataframe
B = dat1.append(dat2)
B

0    1    2  3
0    264  202  304  0
1    293  224  240  0
2    219  243  233  0
3    267  210  219  0
4    310  201  199  0
..   ...  ...  ... ..
415   78  474  448  1
416   59  533  408  1
417  106  416  372  1
418  120  193  192  1
419   70  205  212  1

[837 rows x 4 columns]

In [25]:
A = B.append(dat3)

In [26]:
A

0    1    2  3
0    264  202  304  0
1    293  224  240  0
2    219  243  233  0
3    267  210  219  0
4    310  201  199  0
..   ...  ...  ... ..
464  381  295  324  2
465  281  330  389  2
466  410  259  331  2
467  281  320  399  2
468  270  291  330  2

[1306 rows x 4 columns]

In [27]:
df=A

In [28]:
df

0    1    2  3
0    264  202  304  0
1    293  224  240  0
2    219  243  233  0
3    267  210  219  0
4    310  201  199  0
..   ...  ...  ... ..
464  381  295  324  2
465  281  330  389  2
466  410  259  331  2
467  281  320  399  2
468  270  291  330  2

[1306 rows x 4 columns]

In [29]:
df.head()

0    1    2  3
0  264  202  304  0
1  293  224  240  0
2  219  243  233  0
3  267  210  219  0
4  310  201  199  0

In [30]:
df.tail()

0    1    2  3
464  381  295  324  2
465  281  330  389  2
466  410  259  331  2
467  281  320  399  2
468  270  291  330  2

In [31]:
#save the predicted data into csv file
csv_data=A.to_csv('FinalFORB.csv', mode='a',header=False,index=False)

In [32]:
#read the data from the previously saved csv file
df = pd.read_csv("FinalFORB.csv",header=None)
df

0    1    2  3
0     264  202  304  0
1     293  224  240  0
2     219  243  233  0
3     267  210  219  0
4     310  201  199  0
...   ...  ...  ... ..
1301  381  295  324  2
1302  281  330  389  2
1303  410  259  331  2
1304  281  320  399  2
1305  270  291  330  2

[1306 rows x 4 columns]

In [33]:
#Check for NaN under a single DataFrame column
df.isnull().values.any()

False

In [34]:
# statistical measures about the data
df.describe()

0            1            2            3
count  1306.000000  1306.000000  1306.000000  1306.000000
mean    261.022971   300.857580   314.470138     1.039816
std      64.822276   120.010668    65.863933     0.823007
min      31.000000    70.000000    77.000000     0.000000
25%     220.250000   230.000000   258.000000     0.000000
50%     262.000000   299.000000   316.000000     1.000000
75%     303.000000   357.000000   368.000000     2.000000
max     483.000000  3562.000000   488.000000     2.000000

In [35]:
X = df.drop(columns=3, axis=1)
Y = df[3]

In [36]:
X

0    1    2
0     264  202  304
1     293  224  240
2     219  243  233
3     267  210  219
4     310  201  199
...   ...  ...  ...
1301  381  295  324
1302  281  330  389
1303  410  259  331
1304  281  320  399
1305  270  291  330

[1306 rows x 3 columns]

In [37]:
Y

0       0
1       0
2       0
3       0
4       0
       ..
1301    2
1302    2
1303    2
1304    2
1305    2
Name: 3, Length: 1306, dtype: int64

In [38]:
X_train,X_test,Y_train,Y_test = train_test_split(X,Y,
                                                 test_size=0.3, random_state = 0)
# describes info about train and test set
print("Number transactions X_train dataset: ", X_train.shape)
print("Number transactions y_train dataset: ", Y_train.shape)
print("Number transactions X_test dataset: ", X_test.shape)
print("Number transactions y_test dataset: ", Y_test.shape)

Number transactions X_train dataset:  (914, 3)
Number transactions y_train dataset:  (914,)
Number transactions X_test dataset:  (392, 3)
Number transactions y_test dataset:  (392,)


In [39]:
from sklearn.linear_model import LogisticRegression 
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC
from sklearn.model_selection import cross_val_score
from sklearn.metrics import accuracy_score,f1_score, classification_report, confusion_matrix , accuracy_score, precision_score, recall_score, f1_score, roc_curve ,roc_auc_score
from xgboost import XGBClassifier
from sklearn.neighbors import KNeighborsClassifier

In [40]:
modelRF = RandomForestClassifier()
modelRF.fit(X_train,Y_train)
# accuracy on training data
X_train_prediction = modelRF.predict(X_train)
train_data_accuracy = accuracy_score(X_train_prediction, Y_train)
print("Applying Random Forest")
#print('Accuracy on Train data : ', train_data_accuracy)

# print('Presion :',precision_score(X_train_prediction,Y_train))

# print('Recall :',recall_score(X_train_prediction,Y_train))

# print('F1 score : ', f1_score(X_train_prediction,Y_train))

# accuracy on test data
X_test_prediction = modelRF.predict(X_test)
test_data_accuracy = accuracy_score(X_test_prediction, Y_test)

print('Accuracy on Test data : ', test_data_accuracy)

print('Precision :', precision_score(Y_test, X_test_prediction, average='weighted'))

print('Recall :', recall_score(Y_test, X_test_prediction, average='weighted'))

print('F1 score : ', f1_score(Y_test, X_test_prediction, average='weighted'))


# get the confusion matrix
conf_mat = confusion_matrix(Y_test, X_test_prediction)
print("Confusion matrix:\n", conf_mat)





Applying Random Forest
Accuracy on Test data :  0.7576530612244898
Precision : 0.7565468000305302
Recall : 0.7576530612244898
F1 score :  0.7491378473407749
Confusion matrix:
 [[108   1   4]
 [  0 105  24]
 [ 23  43  84]]


In [41]:
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score

modelknn = KNeighborsClassifier()
modelknn.fit(X_train, Y_train)

# accuracy on training data
X_train_prediction = modelknn.predict(X_train)
train_data_accuracy = accuracy_score(X_train_prediction, Y_train)

print('\nResults obtained for the knn')
print('\nResults obtained on Training Data')
print('Accuracy on Train data : ', train_data_accuracy)

print('Presion :', precision_score(Y_train, X_train_prediction, average='weighted'))
print('Recall :', recall_score(Y_train, X_train_prediction, average='weighted'))
print('F1 score : ', f1_score(Y_train, X_train_prediction, average='weighted'))

# Accuracy on test data
X_test_prediction = modelknn.predict(X_test)
test_data_accuracy = accuracy_score(X_test_prediction, Y_test)

print('\nResults obtained on Testing Data')
print('Accuracy on Test data : ', test_data_accuracy)

print('Presion :', precision_score(Y_test, X_test_prediction, average='weighted'))
print('Recall :', recall_score(Y_test, X_test_prediction, average='weighted'))
print('F1 score : ', f1_score(Y_test, X_test_prediction, average='weighted'))
# get the confusion matrix
conf_mat = confusion_matrix(Y_test, X_test_prediction)
print("Confusion matrix:\n", conf_mat)



Results obtained for the knn

Results obtained on Training Data
Accuracy on Train data :  0.7986870897155361
Presion : 0.7951623727286923
Recall : 0.7986870897155361
F1 score :  0.795061573728586

Results obtained on Testing Data
Accuracy on Test data :  0.6836734693877551
Presion : 0.6746628991559434
Recall : 0.6836734693877551
F1 score :  0.6768158155507759
Confusion matrix:
 [[106   1   6]
 [  4  79  46]
 [ 23  44  83]]


In [42]:
modelDT = DecisionTreeClassifier(max_depth=9)
modelDT.fit(X_train,Y_train)



# accuracy on training data
X_train_prediction = modelDT.predict(X_train)
train_data_accuracy = accuracy_score(X_train_prediction ,Y_train)

print('Accuracy on Train data : ', train_data_accuracy)

print('Presion :',precision_score(X_train_prediction,Y_train,average='weighted'))

print('Recall :',recall_score(X_train_prediction,Y_train,average='weighted'))

print('F1 score : ', f1_score(X_train_prediction,Y_train,average='weighted'))

# accuracy on test data
X_test_prediction = modelRF.predict(X_test)
test_data_accuracy = accuracy_score(X_test_prediction, Y_test)

print('Accuracy on Test data : ', test_data_accuracy)

print('Presion :',precision_score(X_test_prediction,Y_test,average='weighted'))
print('Recall :',recall_score(X_test_prediction,Y_test,average='weighted'))

print('F1 score : ', f1_score(X_test_prediction,Y_test,average='weighted'))

Accuracy on Train data :  0.8435448577680525
Presion : 0.8544699202356556
Recall : 0.8435448577680525
F1 score :  0.8457319812325735
Accuracy on Test data :  0.7576530612244898
Presion : 0.7887821673225783
Recall : 0.7576530612244898
F1 score :  0.7661682751082046


In [43]:
from sklearn.naive_bayes import GaussianNB

modelNB = GaussianNB()
modelNB.fit(X_train,Y_train)

# accuracy on training data
X_train_prediction = modelNB.predict(X_train)
train_data_accuracy = accuracy_score(X_train_prediction ,Y_train)

print('Accuracy on Train data : ', train_data_accuracy)

print('Presion :',precision_score(X_train_prediction,Y_train,average='weighted'))

print('Recall :',recall_score(X_train_prediction,Y_train,average='weighted'))

print('F1 score : ', f1_score(X_train_prediction,Y_train,average='weighted'))

# accuracy on test data
X_test_prediction = modelNB.predict(X_test)
test_data_accuracy = accuracy_score(X_test_prediction, Y_test)

print('Accuracy on Test data : ', test_data_accuracy)

print('Presion :',precision_score(X_test_prediction,Y_test,average='weighted'))
print('Recall :',recall_score(X_test_prediction,Y_test,average='weighted'))

print('F1 score : ', f1_score(X_test_prediction,Y_test,average='weighted'))

# confusion matrix
cm = confusion_matrix(Y_test, X_test_prediction)
print('Confusion Matrix : ')
print(cm)

Accuracy on Train data :  0.6433260393873085
Presion : 0.8548895902348473
Recall : 0.6433260393873085
F1 score :  0.7112218383003757
Accuracy on Test data :  0.5969387755102041
Presion : 0.799753875618986
Recall : 0.5969387755102041
F1 score :  0.663672532636668
Confusion Matrix : 
[[111   1   1]
 [  5 104  20]
 [ 24 107  19]]
