In [1]:
import numpy as np
import pandas as pd                               
import os
import csv
import cv2
import matplotlib.pyplot as plt
from sklearn.cluster import KMeans
from sklearn.model_selection import train_test_split
from sklearn import svm, datasets
from sklearn.metrics import classification_report
from sklearn.tree import DecisionTreeClassifier
import sklearn.metrics as metrics 
from sklearn.metrics import accuracy_score

In [2]:
#Path of dataset
Eating="C:/Users/Aditya/Downloads/CVCP/CV_DATASET/Eating_Images"
Walking="C:/Users/Aditya/Downloads/CVCP/CV_DATASET/Walking Images"
ChitChat="C:/Users/Aditya/Downloads/CVCP/CV_DATASET/Chit chat"

In [3]:
#Applying BRISK Feature descriptor on folder1
i=0
for filename in os.listdir(Eating):
    #path
    path=os.path.join(Eating,filename)
    a=cv2.imread(path)
    
    #resize image
    resize=(256,256)
    img=cv2.resize(a,resize)
    
    #gray image
    gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
    img2= cv2.GaussianBlur(gray,(5,5),0)#gaussian Image
        
    # creating a Histograms Equalization of a image using cv2.equalizeHist()
    equ = cv2.equalizeHist(img2)
    
    kernelx = np.array([[1,1,1],[0,0,0],[-1,-1,-1]]) 
    kernely = np.array([[-1,0,1],[-1,0,1],[-1,0,1]])
    #Horizontal 
    img_prewittx = cv2.filter2D(equ, -1, kernelx)
    img_prewitty = cv2.filter2D(equ, -1, kernely)
    #Vertical
    img_prewitt = img_prewittx + img_prewitty
    #brisk code for feature descriptor
    brisk = cv2.BRISK_create()
    keypoint,descriptor = brisk.detectAndCompute(img_prewitt,None)
    

    
    #convert the descriptor array into a dataframe format
    out=pd.DataFrame(descriptor)
    print("descriptor shape ",i," : ", out.shape)
    i=i+1
  
    #drop first coloumn as it's the no of feature detected. Not required.
    #append to the csv file
    csv_data=out.to_csv('folder1BRISK.csv', mode='a', header=False,index=False)

descriptor shape  0  :  (928, 64)
descriptor shape  1  :  (1021, 64)
descriptor shape  2  :  (473, 64)
descriptor shape  3  :  (441, 64)
descriptor shape  4  :  (599, 64)
descriptor shape  5  :  (627, 64)
descriptor shape  6  :  (654, 64)
descriptor shape  7  :  (755, 64)
descriptor shape  8  :  (538, 64)
descriptor shape  9  :  (598, 64)
descriptor shape  10  :  (747, 64)
descriptor shape  11  :  (698, 64)
descriptor shape  12  :  (610, 64)
descriptor shape  13  :  (728, 64)
descriptor shape  14  :  (764, 64)
descriptor shape  15  :  (528, 64)
descriptor shape  16  :  (675, 64)
descriptor shape  17  :  (595, 64)
descriptor shape  18  :  (561, 64)
descriptor shape  19  :  (746, 64)
descriptor shape  20  :  (685, 64)
descriptor shape  21  :  (497, 64)
descriptor shape  22  :  (686, 64)
descriptor shape  23  :  (990, 64)
descriptor shape  24  :  (1224, 64)
descriptor shape  25  :  (586, 64)
descriptor shape  26  :  (1089, 64)
descriptor shape  27  :  (724, 64)
descriptor shape  28  :  (9

descriptor shape  230  :  (810, 64)
descriptor shape  231  :  (755, 64)
descriptor shape  232  :  (708, 64)
descriptor shape  233  :  (832, 64)
descriptor shape  234  :  (584, 64)
descriptor shape  235  :  (543, 64)
descriptor shape  236  :  (570, 64)
descriptor shape  237  :  (459, 64)
descriptor shape  238  :  (375, 64)
descriptor shape  239  :  (645, 64)
descriptor shape  240  :  (601, 64)
descriptor shape  241  :  (798, 64)
descriptor shape  242  :  (443, 64)
descriptor shape  243  :  (606, 64)
descriptor shape  244  :  (683, 64)
descriptor shape  245  :  (744, 64)
descriptor shape  246  :  (500, 64)
descriptor shape  247  :  (1261, 64)
descriptor shape  248  :  (481, 64)
descriptor shape  249  :  (1055, 64)
descriptor shape  250  :  (582, 64)
descriptor shape  251  :  (680, 64)
descriptor shape  252  :  (815, 64)
descriptor shape  253  :  (792, 64)
descriptor shape  254  :  (756, 64)
descriptor shape  255  :  (463, 64)
descriptor shape  256  :  (540, 64)
descriptor shape  257  :  

In [4]:
#reading previously saved feature descriptor csv file of folder1 and save it into a dataframe
data1 = pd.read_csv('folder1BRISK.csv',header=None,dtype='uint8')

data1=data1.astype(np.uint8) 
data1

0    1    2    3    4    5    6    7    8    9   ...   54   55   56  \
0       240   63  231  233    0    0    0    0    0    0  ...  244  252  255   
1       203  255  255  243  251    0    0  128  239  193  ...  255  253   56   
2       148   11  223    7    0    0   64    0    0    0  ...  126  246  223   
3       176  123  223  225  107    0    0    0    0    0  ...  102   50  221   
4       176   27  223  100  106  192    0    0    0    0  ...  106   58  223   
...     ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...   
297232   71  230   36  159  148   63  169  148  255    9  ...  145  240  124   
297233  107  183  190  215  211  163  129  254   70   13  ...   10   18    7   
297234  180    3  192  236   15   70   76    0    0  230  ...   16   16  168   
297235    0  123   14    0    0  216  123   16  160    0  ...   76   12  130   
297236  127  132   56  246  255  239  255  136   16    1  ...    0   88   46   

         57   58   59   60   61   62   63  
0       255  126   53    0    0    0    0  
1         4   64   32   18    0    0    0  
2       108  102    0    0    0    0    0  
3        65    0    0    0    0    0    0  
4       108   96   36    0    0    0    0  
...     ...  ...  ...  ...  ...  ...  ...  
297232    7    0  128    0  253  125  127  
297233    0    0  197   99    0  192  255  
297234  195    0    0  224   58   51   48  
297235  226   65    0    0   32  241  246  
297236  251   97   32    0   32   96    0  

[297237 rows x 64 columns]

In [5]:
#Applying BRISK Feature descriptor on folder2
i=0
for filename in os.listdir(Walking):
    
    path=os.path.join(Walking,filename)
    a=cv2.imread(path)
    
    #resize image
    resize=(256,256)
    img=cv2.resize(a,resize)
    #gray image
    gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
    img2= cv2.GaussianBlur(gray,(5,5),0)#gaussian Image
        
    # creating a Histograms Equalization of a image using cv2.equalizeHist()
    equ = cv2.equalizeHist(img2)
    
    kernelx = np.array([[1,1,1],[0,0,0],[-1,-1,-1]]) 
    kernely = np.array([[-1,0,1],[-1,0,1],[-1,0,1]])
    #Horizontal 
    img_prewittx = cv2.filter2D(equ, -1, kernelx)
    img_prewitty = cv2.filter2D(equ, -1, kernely)
    #Vertical
    img_prewitt = img_prewittx + img_prewitty

    #brisk code for feature descriptor
    brisk = cv2.BRISK_create()
    keypoint,descriptor = brisk.detectAndCompute(img_prewitt,None)
    

    
    #convert the descriptor array into a dataframe format
    out=pd.DataFrame(descriptor)
    print("descriptor shape ",i," : ", out.shape)
    i=i+1
    #drop first coloumn as it's the no of feature detected. Not required.
    #append to the csv file
    csv_data=out.to_csv('folder2BRISK.csv', mode='a', header=False,index=False)

descriptor shape  0  :  (130, 64)
descriptor shape  1  :  (104, 64)
descriptor shape  2  :  (130, 64)
descriptor shape  3  :  (909, 64)
descriptor shape  4  :  (166, 64)
descriptor shape  5  :  (86, 64)
descriptor shape  6  :  (550, 64)
descriptor shape  7  :  (200, 64)
descriptor shape  8  :  (183, 64)
descriptor shape  9  :  (275, 64)
descriptor shape  10  :  (832, 64)
descriptor shape  11  :  (849, 64)
descriptor shape  12  :  (1881, 64)
descriptor shape  13  :  (356, 64)
descriptor shape  14  :  (738, 64)
descriptor shape  15  :  (499, 64)
descriptor shape  16  :  (193, 64)
descriptor shape  17  :  (633, 64)
descriptor shape  18  :  (156, 64)
descriptor shape  19  :  (234, 64)
descriptor shape  20  :  (212, 64)
descriptor shape  21  :  (128, 64)
descriptor shape  22  :  (354, 64)
descriptor shape  23  :  (1577, 64)
descriptor shape  24  :  (937, 64)
descriptor shape  25  :  (937, 64)
descriptor shape  26  :  (472, 64)
descriptor shape  27  :  (426, 64)
descriptor shape  28  :  (389

descriptor shape  234  :  (662, 64)
descriptor shape  235  :  (1811, 64)
descriptor shape  236  :  (400, 64)
descriptor shape  237  :  (242, 64)
descriptor shape  238  :  (762, 64)
descriptor shape  239  :  (780, 64)
descriptor shape  240  :  (371, 64)
descriptor shape  241  :  (200, 64)
descriptor shape  242  :  (319, 64)
descriptor shape  243  :  (342, 64)
descriptor shape  244  :  (475, 64)
descriptor shape  245  :  (503, 64)
descriptor shape  246  :  (555, 64)
descriptor shape  247  :  (691, 64)
descriptor shape  248  :  (750, 64)
descriptor shape  249  :  (765, 64)
descriptor shape  250  :  (868, 64)
descriptor shape  251  :  (703, 64)
descriptor shape  252  :  (191, 64)
descriptor shape  253  :  (270, 64)
descriptor shape  254  :  (261, 64)
descriptor shape  255  :  (490, 64)
descriptor shape  256  :  (432, 64)
descriptor shape  257  :  (509, 64)
descriptor shape  258  :  (1143, 64)
descriptor shape  259  :  (363, 64)
descriptor shape  260  :  (443, 64)
descriptor shape  261  :  

In [6]:
#reading previously saved feature descriptor csv file of folder2 and save it into a dataframe
data2= pd.read_csv('folder2BRISK.csv',header=None,dtype='uint8')
data2=data2.astype(np.uint8)
data2

0    1    2    3    4    5    6   7   8   9   ...   54   55   56  \
0       128   59  199  233   14    0    0   0   0   0  ...  251  249   14   
1       188    1    0  240  255  207   28   0   0   0  ...  191  245   36   
2       240   27    0    0   76  220  120   0   0   0  ...  255  183   73   
3       176   59  195  239  239   15    0   0   0   0  ...  255  247  253   
4       176   59  215  239  230    0    0   0   0   0  ...  255  211   97   
...     ...  ...  ...  ...  ...  ...  ...  ..  ..  ..  ...  ...  ...  ...   
196837  176   59  215   96  224   30    0   0   0   0  ...    0    0    0   
196838  176   59  215  225   14    0    0   0   0   0  ...    0    0    0   
196839  176  255  255  231    0    0    0   0   0   0  ...    4    0    0   
196840  176   25  223  239  227   19    0   0   0   0  ...    0   64  118   
196841  176   25  219  228  111    2    0   0   0   0  ...    0  192  231   

         57   58   59  60  61  62  63  
0         0    0    0   0   0   0   0  
1         0    0    0   0   0   0   0  
2        16  218   97   0   0   0   0  
3        83    0    0   0   0   0   0  
4       240  233  180  31   0   0   0  
...     ...  ...  ...  ..  ..  ..  ..  
196837    0  136  225  58   0   0   0  
196838  199  227   52   0   0   0   0  
196839  128  231  103   0   0   0   0  
196840  199    0    0   0   0   0   0  
196841   83    0    0   0   0   0   0  

[196842 rows x 64 columns]

In [7]:
#Applying BRISK Feature descriptor on folder2
i=0
for filename in os.listdir(ChitChat):
    
    path=os.path.join(ChitChat,filename)
    a=cv2.imread(path)
    
    #resize image
    resize=(256,256)
    img=cv2.resize(a,resize)
    
    #gray image
    gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
    img2= cv2.GaussianBlur(gray,(5,5),0)#gaussian Image
        
    # creating a Histograms Equalization of a image using cv2.equalizeHist()
    equ = cv2.equalizeHist(img2)
    kernelx = np.array([[1,1,1],[0,0,0],[-1,-1,-1]]) 
    kernely = np.array([[-1,0,1],[-1,0,1],[-1,0,1]])
    #Horizontal 
    img_prewittx = cv2.filter2D(equ, -1, kernelx)
    img_prewitty = cv2.filter2D(equ, -1, kernely)
    #Vertical
    img_prewitt = img_prewittx + img_prewitty 


    #brisk code for feature descriptor
    brisk = cv2.BRISK_create()
    keypoint,descriptor = brisk.detectAndCompute(img_prewitt,None)
    

    
    #convert the descriptor array into a dataframe format
    out=pd.DataFrame(descriptor)
    print("descriptor shape ",i," : ", out.shape)
    i=i+1
    #drop first coloumn as it's the no of feature detected. Not required.
    #append to the csv file
    csv_data=out.to_csv('folder3BRISK.csv', mode='a', header=False,index=False)

descriptor shape  0  :  (633, 64)
descriptor shape  1  :  (1085, 64)
descriptor shape  2  :  (930, 64)
descriptor shape  3  :  (901, 64)
descriptor shape  4  :  (1244, 64)
descriptor shape  5  :  (1165, 64)
descriptor shape  6  :  (542, 64)
descriptor shape  7  :  (1536, 64)
descriptor shape  8  :  (1225, 64)
descriptor shape  9  :  (636, 64)
descriptor shape  10  :  (986, 64)
descriptor shape  11  :  (682, 64)
descriptor shape  12  :  (1179, 64)
descriptor shape  13  :  (719, 64)
descriptor shape  14  :  (663, 64)
descriptor shape  15  :  (1249, 64)
descriptor shape  16  :  (964, 64)
descriptor shape  17  :  (1492, 64)
descriptor shape  18  :  (1242, 64)
descriptor shape  19  :  (1369, 64)
descriptor shape  20  :  (745, 64)
descriptor shape  21  :  (1098, 64)
descriptor shape  22  :  (1015, 64)
descriptor shape  23  :  (1245, 64)
descriptor shape  24  :  (769, 64)
descriptor shape  25  :  (1346, 64)
descriptor shape  26  :  (1269, 64)
descriptor shape  27  :  (913, 64)
descriptor shap

descriptor shape  228  :  (1405, 64)
descriptor shape  229  :  (1041, 64)
descriptor shape  230  :  (1228, 64)
descriptor shape  231  :  (1314, 64)
descriptor shape  232  :  (617, 64)
descriptor shape  233  :  (615, 64)
descriptor shape  234  :  (1296, 64)
descriptor shape  235  :  (556, 64)
descriptor shape  236  :  (459, 64)
descriptor shape  237  :  (649, 64)
descriptor shape  238  :  (791, 64)
descriptor shape  239  :  (694, 64)
descriptor shape  240  :  (816, 64)
descriptor shape  241  :  (783, 64)
descriptor shape  242  :  (798, 64)
descriptor shape  243  :  (788, 64)
descriptor shape  244  :  (853, 64)
descriptor shape  245  :  (736, 64)
descriptor shape  246  :  (935, 64)
descriptor shape  247  :  (1026, 64)
descriptor shape  248  :  (742, 64)
descriptor shape  249  :  (766, 64)
descriptor shape  250  :  (1044, 64)
descriptor shape  251  :  (1095, 64)
descriptor shape  252  :  (783, 64)
descriptor shape  253  :  (1137, 64)
descriptor shape  254  :  (1026, 64)
descriptor shape  

descriptor shape  453  :  (379, 64)
descriptor shape  454  :  (973, 64)
descriptor shape  455  :  (707, 64)
descriptor shape  456  :  (1195, 64)
descriptor shape  457  :  (806, 64)
descriptor shape  458  :  (702, 64)
descriptor shape  459  :  (701, 64)
descriptor shape  460  :  (886, 64)
descriptor shape  461  :  (688, 64)
descriptor shape  462  :  (690, 64)
descriptor shape  463  :  (719, 64)
descriptor shape  464  :  (1118, 64)
descriptor shape  465  :  (1426, 64)
descriptor shape  466  :  (1271, 64)
descriptor shape  467  :  (718, 64)
descriptor shape  468  :  (677, 64)


In [8]:
#reading previously saved feature descriptor csv file of folder2 and save it into a dataframe
data3= pd.read_csv('folder3BRISK.csv',header=None,dtype='uint8')
data3=data3.astype(np.uint8)
data3

0    1    2    3    4    5    6    7    8    9   ...   54   55   56  \
0       176    1  223  239  239  195    7    0    0    0  ...  216   78    2   
1       180    0   81   46   38   66   68    1  241  242  ...  103    7  249   
2         0    2  128  239   15    0    0    0  252  248  ...   71    3  160   
3       148  251  223    3    0    0    0    0  225    0  ...  207  199  129   
4       180   59  199  239    4    0    0   96    0  238  ...  223   23    0   
...     ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...   
490360    6  104   93  175  161   65   67    8  253  255  ...  206  222    7   
490361  180   27  215  224  239  202    0    0    0  128  ...  228  255  127   
490362   32  123  255  239  227  195    7    0  134  140  ...    3    0  132   
490363   32  123  134  201  205  224  127    6    0    0  ...  241  239  249   
490364    7    0    0    0    8   28  120  124  112    0  ...  127  243  253   

         57   58   59   60   61   62   63  
0         0    0  192   96  186  185   51  
1       250   12    0  209  252  255   22  
2        42   20  138  126   13  128  223  
3        32   65   36   27    0  128  255  
4       128  129  196  115  193  192    1  
...     ...  ...  ...  ...  ...  ...  ...  
490360   64  255  127   26   73  110  205  
490361    3    0  224   48    0   64  254  
490362    3    0  201  100   24  145  255  
490363  190  223  255    1    0  115  114  
490364   53  218    5    1    0  113  242  

[490365 rows x 64 columns]

In [9]:
#append all the class wise feature descriptor data into one data frame
data=data1.append(data2)
data

C:\Users\Aditya\AppData\Local\Temp\ipykernel_13400\1996419536.py:2: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  data=data1.append(data2)


0    1    2    3    4    5   6    7    8    9   ...   54   55   56  \
0       240   63  231  233    0    0   0    0    0    0  ...  244  252  255   
1       203  255  255  243  251    0   0  128  239  193  ...  255  253   56   
2       148   11  223    7    0    0  64    0    0    0  ...  126  246  223   
3       176  123  223  225  107    0   0    0    0    0  ...  102   50  221   
4       176   27  223  100  106  192   0    0    0    0  ...  106   58  223   
...     ...  ...  ...  ...  ...  ...  ..  ...  ...  ...  ...  ...  ...  ...   
196837  176   59  215   96  224   30   0    0    0    0  ...    0    0    0   
196838  176   59  215  225   14    0   0    0    0    0  ...    0    0    0   
196839  176  255  255  231    0    0   0    0    0    0  ...    4    0    0   
196840  176   25  223  239  227   19   0    0    0    0  ...    0   64  118   
196841  176   25  219  228  111    2   0    0    0    0  ...    0  192  231   

         57   58   59  60  61  62  63  
0       255  126   53   0   0   0   0  
1         4   64   32  18   0   0   0  
2       108  102    0   0   0   0   0  
3        65    0    0   0   0   0   0  
4       108   96   36   0   0   0   0  
...     ...  ...  ...  ..  ..  ..  ..  
196837    0  136  225  58   0   0   0  
196838  199  227   52   0   0   0   0  
196839  128  231  103   0   0   0   0  
196840  199    0    0   0   0   0   0  
196841   83    0    0   0   0   0   0  

[494079 rows x 64 columns]

In [10]:
data=data2.append(data3)
data

C:\Users\Aditya\AppData\Local\Temp\ipykernel_13400\3845846524.py:1: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  data=data2.append(data3)


0    1    2    3    4    5    6    7    8    9   ...   54   55   56  \
0       128   59  199  233   14    0    0    0    0    0  ...  251  249   14   
1       188    1    0  240  255  207   28    0    0    0  ...  191  245   36   
2       240   27    0    0   76  220  120    0    0    0  ...  255  183   73   
3       176   59  195  239  239   15    0    0    0    0  ...  255  247  253   
4       176   59  215  239  230    0    0    0    0    0  ...  255  211   97   
...     ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...   
490360    6  104   93  175  161   65   67    8  253  255  ...  206  222    7   
490361  180   27  215  224  239  202    0    0    0  128  ...  228  255  127   
490362   32  123  255  239  227  195    7    0  134  140  ...    3    0  132   
490363   32  123  134  201  205  224  127    6    0    0  ...  241  239  249   
490364    7    0    0    0    8   28  120  124  112    0  ...  127  243  253   

         57   58   59   60  61   62   63  
0         0    0    0    0   0    0    0  
1         0    0    0    0   0    0    0  
2        16  218   97    0   0    0    0  
3        83    0    0    0   0    0    0  
4       240  233  180   31   0    0    0  
...     ...  ...  ...  ...  ..  ...  ...  
490360   64  255  127   26  73  110  205  
490361    3    0  224   48   0   64  254  
490362    3    0  201  100  24  145  255  
490363  190  223  255    1   0  115  114  
490364   53  218    5    1   0  113  242  

[687207 rows x 64 columns]

In [11]:
#save appended data into a csv file
csv_data=data.to_csv('finalDataBRISK.csv', mode='a', header=False,index=False)

In [12]:
#read the data from the previously saved csv file
data = pd.read_csv('finalDataBRISK.csv',header=None)
data

0    1    2    3    4    5    6    7    8    9   ...   54   55   56  \
0       128   59  199  233   14    0    0    0    0    0  ...  251  249   14   
1       188    1    0  240  255  207   28    0    0    0  ...  191  245   36   
2       240   27    0    0   76  220  120    0    0    0  ...  255  183   73   
3       176   59  195  239  239   15    0    0    0    0  ...  255  247  253   
4       176   59  215  239  230    0    0    0    0    0  ...  255  211   97   
...     ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...   
687202    6  104   93  175  161   65   67    8  253  255  ...  206  222    7   
687203  180   27  215  224  239  202    0    0    0  128  ...  228  255  127   
687204   32  123  255  239  227  195    7    0  134  140  ...    3    0  132   
687205   32  123  134  201  205  224  127    6    0    0  ...  241  239  249   
687206    7    0    0    0    8   28  120  124  112    0  ...  127  243  253   

         57   58   59   60  61   62   63  
0         0    0    0    0   0    0    0  
1         0    0    0    0   0    0    0  
2        16  218   97    0   0    0    0  
3        83    0    0    0   0    0    0  
4       240  233  180   31   0    0    0  
...     ...  ...  ...  ...  ..  ...  ...  
687202   64  255  127   26  73  110  205  
687203    3    0  224   48   0   64  254  
687204    3    0  201  100  24  145  255  
687205  190  223  255    1   0  115  114  
687206   53  218    5    1   0  113  242  

[687207 rows x 64 columns]

In [13]:
#Applying Kmeans
kmeans = KMeans(n_clusters=3)
kmeans.fit(data)

KMeans(n_clusters=3)

In [14]:
#save the model to disk
import pickle
filename = 'Kmeans_CL_2_ModelBRISK.sav'
pickle.dump(kmeans, open(filename, 'wb'))

In [15]:
#calculate histogram of trained kmeans
hist = np.histogram(kmeans.labels_,bins=[0,1,2,3])

print("Histogram of trained kmeans")
print(hist, "\n")

Histogram of trained kmeans
(array([205757, 248432, 233018], dtype=int64), array([0, 1, 2, 3])) 



In [16]:
#performing kmeans prediction on the Abnormal with the pretrained kmeans model

#initialising i=0; as it is the first class
i=0
data=[]
#k=0

for filename in os.listdir(Eating):
    #path
    path=os.path.join(Eating,filename)
    a=cv2.imread(path)
    #resize=(256,256)
    #img=cv2.resize(img,resize)
    #gray image
    gray = cv2.cvtColor(a, cv2.COLOR_BGR2GRAY)

    # creating a Histograms Equalization for folder1(Fall)
    equ = cv2.equalizeHist(gray)

    #Applyeda
  
    #Applying Sift  Discriptor Abnormal folder
    kernelx = np.array([[1,1,1],[0,0,0],[-1,-1,-1]]) #kernels for prewitt edge detection
    kernely = np.array([[-1,0,1],[-1,0,1],[-1,0,1]])
    img_prewittx = cv2.filter2D(equ, -1, kernelx)#Horizontal 
    img_prewitty = cv2.filter2D(equ, -1, kernely)#Vertical
    img_prewitt = img_prewittx + img_prewitty    
    
    brisk = cv2.BRISK_create()
    keypoint,descriptor = brisk.detectAndCompute(gray,None)
    

    out=pd.DataFrame(descriptor)

    array_double = np.array(out, dtype=np.double)
    try:
        a=kmeans.predict(array_double)
    except:
        print(filename)
    hist=np.histogram(a,bins=[0,1,2,3])

    #append the dataframe into the array
    data.append(hist[0])


#convert Array to Dataframe and append to the list
Output = pd.DataFrame(data)
#add row class
Output["Class"] = i
csv_data=Output.to_csv('finalFolder1BRISK.csv', mode='a',header=False,index=False)

In [17]:
#performing kmeans prediction on the Abnormal with the pretrained kmeans model

#initialising i=0; as it is the first class
i=1
data=[]
#k=0

for filename in os.listdir(Walking):
    #path
    path=os.path.join(Walking,filename)
    a=cv2.imread(path)
    #resize=(256,256)
    #img=cv2.resize(img,resize)
    #gray image
    gray = cv2.cvtColor(a, cv2.COLOR_BGR2GRAY)

    # creating a Histograms Equalization for folder1(Fall)
    equ = cv2.equalizeHist(gray)

    #Applyeda
  
    #Applying Sift  Discriptor Abnormal folder
    kernelx = np.array([[1,1,1],[0,0,0],[-1,-1,-1]]) #kernels for prewitt edge detection
    kernely = np.array([[-1,0,1],[-1,0,1],[-1,0,1]])
    img_prewittx = cv2.filter2D(equ, -1, kernelx)#Horizontal 
    img_prewitty = cv2.filter2D(equ, -1, kernely)#Vertical
    img_prewitt = img_prewittx + img_prewitty    
    
    brisk = cv2.BRISK_create()
    keypoint,descriptor = brisk.detectAndCompute(gray,None)
    

    out=pd.DataFrame(descriptor)

    array_double = np.array(out, dtype=np.double)
    try:
        a=kmeans.predict(array_double)
    except:
        print(filename)
    hist=np.histogram(a,bins=[0,1,2,3])

    #append the dataframe into the array
    data.append(hist[0])


#convert Array to Dataframe and append to the list
Output = pd.DataFrame(data)
#add row class
Output["Class"] = i
csv_data=Output.to_csv('finalFolder2BRISK.csv', mode='a',header=False,index=False)

In [18]:
#performing kmeans prediction on the Abnormal with the pretrained kmeans model

#initialising i=0; as it is the first class
i=2
data=[]
#k=0

for filename in os.listdir(ChitChat):
    #path
    path=os.path.join(ChitChat,filename)
    a=cv2.imread(path)
    #resize=(256,256)
    #img=cv2.resize(img,resize)
    #gray image
    gray = cv2.cvtColor(a, cv2.COLOR_BGR2GRAY)

    # creating a Histograms Equalization for folder1(Fall)
    equ = cv2.equalizeHist(gray)

    #Applyeda
  
    #Applying Sift  Discriptor Abnormal folder
    kernelx = np.array([[1,1,1],[0,0,0],[-1,-1,-1]]) #kernels for prewitt edge detection
    kernely = np.array([[-1,0,1],[-1,0,1],[-1,0,1]])
    img_prewittx = cv2.filter2D(equ, -1, kernelx)#Horizontal 
    img_prewitty = cv2.filter2D(equ, -1, kernely)#Vertical
    img_prewitt = img_prewittx + img_prewitty    
    
    brisk = cv2.BRISK_create()
    keypoint,descriptor = brisk.detectAndCompute(gray,None)
    

    out=pd.DataFrame(descriptor)

    array_double = np.array(out, dtype=np.double)
    try:
        a=kmeans.predict(array_double)
    except:
        print(filename)
    hist=np.histogram(a,bins=[0,1,2,3])

    #append the dataframe into the array
    data.append(hist[0])


#convert Array to Dataframe and append to the list
Output = pd.DataFrame(data)
#add row class
Output["Class"] = i
csv_data=Output.to_csv('finalFolder3BRISK.csv', mode='a',header=False,index=False)

In [19]:
#Displaying the kmeans predicted data of folder1
print("Eating")
dat1= pd.read_csv('finalFolder1BRISK.csv',header=None)
print(dat1)

Eating
       0    1    2  3
0    102  191  104  0
1    107  170  165  0
2     52   82   93  0
3     56   98   67  0
4     63  123  115  0
..   ...  ...  ... ..
412   91  164  171  0
413  104  141  134  0
414   80  111  100  0
415   68   97   82  0
416   70  108  175  0

[417 rows x 4 columns]


In [20]:
#Displaying the kmeans predicted data of folder2
print("Walking")
dat2= pd.read_csv('finalFolder2BRISK.csv',header=None)
print(dat2)

Walking
        0     1     2  3
0      93    95    92  1
1      50    62    49  1
2      31    11    41  1
3    1034  1220  1879  1
4      30    76    55  1
..    ...   ...   ... ..
415    41    92    62  1
416    94    98    80  1
417    74    31   133  1
418    21    14    32  1
419    16    26    10  1

[420 rows x 4 columns]


In [21]:
#Displaying the kmeans predicted data of folder2
print("Chit-Chatting")
dat3= pd.read_csv('finalFolder3BRISK.csv',header=None)
print(dat3)

Chit-Chatting
        0     1     2  3
0     383   471   521  2
1     355   358   720  2
2     286   299   536  2
3     280   396   477  2
4    1153  1280  1654  2
..    ...   ...   ... ..
464   232   218   186  2
465   842   716  1174  2
466   454   498   545  2
467   507   557  1061  2
468    73    66   165  2

[469 rows x 4 columns]


In [22]:
#appending All kmeans predicted data into 1 dataframe
B = dat1.append(dat2)
B

C:\Users\Aditya\AppData\Local\Temp\ipykernel_13400\1676112912.py:2: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  B = dat1.append(dat2)


0    1    2  3
0    102  191  104  0
1    107  170  165  0
2     52   82   93  0
3     56   98   67  0
4     63  123  115  0
..   ...  ...  ... ..
415   41   92   62  1
416   94   98   80  1
417   74   31  133  1
418   21   14   32  1
419   16   26   10  1

[837 rows x 4 columns]

In [23]:
A = B.append(dat3)

C:\Users\Aditya\AppData\Local\Temp\ipykernel_13400\2751033233.py:1: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  A = B.append(dat3)


In [24]:
#save the predicted data into csv file
csv_data=A.to_csv('FinalFBRISK.csv', mode='a',header=False,index=False)

In [25]:
#read the data from the previously saved csv file
df = pd.read_csv("FinalFBRISK.csv",header=None)
df

0    1     2  3
0     102  191   104  0
1     107  170   165  0
2      52   82    93  0
3      56   98    67  0
4      63  123   115  0
...   ...  ...   ... ..
1301  232  218   186  2
1302  842  716  1174  2
1303  454  498   545  2
1304  507  557  1061  2
1305   73   66   165  2

[1306 rows x 4 columns]

In [26]:
#Check for NaN under a single DataFrame column
df.isnull().values.any()

False

In [27]:
# statistical measures about the data
df.describe()

0              1              2            3
count    1306.000000    1306.000000    1306.000000  1306.000000
mean      593.058193     632.800153     881.820827     1.039816
std      4594.781237    3623.788028    5719.232298     0.823007
min         1.000000       2.000000       0.000000     0.000000
25%        55.000000     101.000000      72.250000     0.000000
50%       105.000000     164.000000     144.000000     1.000000
75%       327.500000     422.750000     467.000000     2.000000
max    146351.000000  110151.000000  176527.000000     2.000000

In [28]:
X = df.drop(columns=3, axis=1)
Y = df[3]

In [29]:
X

0    1     2
0     102  191   104
1     107  170   165
2      52   82    93
3      56   98    67
4      63  123   115
...   ...  ...   ...
1301  232  218   186
1302  842  716  1174
1303  454  498   545
1304  507  557  1061
1305   73   66   165

[1306 rows x 3 columns]

In [30]:
Y

0       0
1       0
2       0
3       0
4       0
       ..
1301    2
1302    2
1303    2
1304    2
1305    2
Name: 3, Length: 1306, dtype: int64

In [31]:
X_train,X_test,Y_train,Y_test = train_test_split(X,Y,
                                                 test_size=0.3, random_state = 0)
# describes info about train and test set
print("Number transactions X_train dataset: ", X_train.shape)
print("Number transactions y_train dataset: ", Y_train.shape)
print("Number transactions X_test dataset: ", X_test.shape)
print("Number transactions y_test dataset: ", Y_test.shape)

Number transactions X_train dataset:  (914, 3)
Number transactions y_train dataset:  (914,)
Number transactions X_test dataset:  (392, 3)
Number transactions y_test dataset:  (392,)


In [32]:
from sklearn.linear_model import LogisticRegression 
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC
from sklearn.model_selection import cross_val_score
from sklearn.metrics import accuracy_score,f1_score, classification_report, confusion_matrix , accuracy_score, precision_score, recall_score, f1_score, roc_curve ,roc_auc_score
from xgboost import XGBClassifier
from sklearn.neighbors import KNeighborsClassifier

In [33]:
#Importing required libraries

import pandas as pd
from sklearn.model_selection import KFold 
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

In [34]:
modelRF = RandomForestClassifier()
modelRF.fit(X_train,Y_train)
# accuracy on training data
X_train_prediction = modelRF.predict(X_train)
train_data_accuracy = accuracy_score(X_train_prediction, Y_train)
print("Applying Random Forest")
#print('Accuracy on Train data : ', train_data_accuracy)

# print('Presion :',precision_score(X_train_prediction,Y_train))

# print('Recall :',recall_score(X_train_prediction,Y_train))

# print('F1 score : ', f1_score(X_train_prediction,Y_train))

# accuracy on test data
X_test_prediction = modelRF.predict(X_test)
test_data_accuracy = accuracy_score(X_test_prediction, Y_test)

print('Accuracy on Test data : ', test_data_accuracy)

print('Precision :', precision_score(Y_test, X_test_prediction, average='weighted'))

print('Recall :', recall_score(Y_test, X_test_prediction, average='weighted'))

print('F1 score : ', f1_score(Y_test, X_test_prediction, average='weighted'))


# get the confusion matrix
conf_mat = confusion_matrix(Y_test, X_test_prediction)
print("Confusion matrix:\n", conf_mat)

Applying Random Forest
Accuracy on Test data :  0.8698979591836735
Precision : 0.8774157390228818
Recall : 0.8698979591836735
F1 score :  0.8713375855526222
Confusion matrix:
 [[101   7   5]
 [ 17 107   5]
 [ 14   3 133]]


In [35]:
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score

modelknn = KNeighborsClassifier()
modelknn.fit(X_train, Y_train)

# accuracy on training data
X_train_prediction = modelknn.predict(X_train)
train_data_accuracy = accuracy_score(X_train_prediction, Y_train)

print('\nResults obtained for the knn')
print('\nResults obtained on Training Data')
print('Accuracy on Train data : ', train_data_accuracy)

print('Presion :', precision_score(Y_train, X_train_prediction, average='weighted'))
print('Recall :', recall_score(Y_train, X_train_prediction, average='weighted'))
print('F1 score : ', f1_score(Y_train, X_train_prediction, average='weighted'))

# Accuracy on test data
X_test_prediction = modelknn.predict(X_test)
test_data_accuracy = accuracy_score(X_test_prediction, Y_test)

print('\nResults obtained on Testing Data')
print('Accuracy on Test data : ', test_data_accuracy)

print('Presion :', precision_score(Y_test, X_test_prediction, average='weighted'))
print('Recall :', recall_score(Y_test, X_test_prediction, average='weighted'))
print('F1 score : ', f1_score(Y_test, X_test_prediction, average='weighted'))
# get the confusion matrix
conf_mat = confusion_matrix(Y_test, X_test_prediction)
print("Confusion matrix:\n", conf_mat)



Results obtained for the knn

Results obtained on Training Data
Accuracy on Train data :  0.8665207877461707
Presion : 0.8665180679696868
Recall : 0.8665207877461707
F1 score :  0.8664947974066637

Results obtained on Testing Data
Accuracy on Test data :  0.8316326530612245
Presion : 0.8437324175697801
Recall : 0.8316326530612245
F1 score :  0.833940608470618
Confusion matrix:
 [[ 97  12   4]
 [ 23  99   7]
 [ 18   2 130]]


C:\Users\Aditya\anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:228: FutureWarning: Unlike other reduction functions (e.g. `skew`, `kurtosis`), the default behavior of `mode` typically preserves the axis it acts along. In SciPy 1.11.0, this behavior will change: the default value of `keepdims` will become False, the `axis` over which the statistic is taken will be eliminated, and the value None will no longer be accepted. Set `keepdims` to True or False to avoid this warning.
  mode, _ = stats.mode(_y[neigh_ind, k], axis=1)
C:\Users\Aditya\anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:228: FutureWarning: Unlike other reduction functions (e.g. `skew`, `kurtosis`), the default behavior of `mode` typically preserves the axis it acts along. In SciPy 1.11.0, this behavior will change: the default value of `keepdims` will become False, the `axis` over which the statistic is taken will be eliminated, and the value None will no longer be accepted. Set `keepd

In [36]:
modelDT = DecisionTreeClassifier(max_depth=9)
modelDT.fit(X_train,Y_train)



# accuracy on training data
X_train_prediction = modelDT.predict(X_train)
train_data_accuracy = accuracy_score(X_train_prediction ,Y_train)

print('Accuracy on Train data : ', train_data_accuracy)

print('Presion :',precision_score(X_train_prediction,Y_train,average='weighted'))

print('Recall :',recall_score(X_train_prediction,Y_train,average='weighted'))

print('F1 score : ', f1_score(X_train_prediction,Y_train,average='weighted'))

# accuracy on test data
X_test_prediction = modelRF.predict(X_test)
test_data_accuracy = accuracy_score(X_test_prediction, Y_test)

print('Accuracy on Test data : ', test_data_accuracy)

print('Presion :',precision_score(X_test_prediction,Y_test,average='weighted'))
print('Recall :',recall_score(X_test_prediction,Y_test,average='weighted'))

print('F1 score : ', f1_score(X_test_prediction,Y_test,average='weighted'))

Accuracy on Train data :  0.9179431072210066
Presion : 0.9228626039254436
Recall : 0.9179431072210066
F1 score :  0.9176943706543967
Accuracy on Test data :  0.8698979591836735
Presion : 0.8719952700158062
Recall : 0.8698979591836735
F1 score :  0.868458332814725


In [37]:
from sklearn.metrics import confusion_matrix

modelSVM = SVC()
modelSVM.fit(X_train,Y_train)

# accuracy on training data
X_train_prediction = modelSVM.predict(X_train)
train_data_accuracy = accuracy_score(X_train_prediction ,Y_train)

print('Accuracy on Train data : ', train_data_accuracy)

print('Presion :',precision_score(X_train_prediction,Y_train,average='weighted'))

print('Recall :',recall_score(X_train_prediction,Y_train,average='weighted'))

print('F1 score : ', f1_score(X_train_prediction,Y_train,average='weighted'))

# accuracy on test data
X_test_prediction = modelSVM.predict(X_test)
test_data_accuracy = accuracy_score(X_test_prediction, Y_test)

print('Accuracy on Test data : ', test_data_accuracy)

print('Presion :',precision_score(X_test_prediction,Y_test,average='weighted'))
print('Recall :',recall_score(X_test_prediction,Y_test,average='weighted'))

print('F1 score : ', f1_score(X_test_prediction,Y_test,average='weighted'))

# confusion matrix
cm = confusion_matrix(Y_test, X_test_prediction)
print('Confusion Matrix : ')
print(cm)

Accuracy on Train data :  0.49671772428884026
Presion : 0.8909353762699552
Recall : 0.49671772428884026
F1 score :  0.581177454250722
Accuracy on Test data :  0.4770408163265306
Presion : 0.8758325423192532
Recall : 0.4770408163265306
F1 score :  0.5514100259657042
Confusion Matrix : 
[[113   0   0]
 [112   3  14]
 [ 78   1  71]]


In [38]:
from sklearn.naive_bayes import GaussianNB

modelNB = GaussianNB()
modelNB.fit(X_train,Y_train)

# accuracy on training data
X_train_prediction = modelNB.predict(X_train)
train_data_accuracy = accuracy_score(X_train_prediction ,Y_train)

print('Accuracy on Train data : ', train_data_accuracy)

print('Presion :',precision_score(X_train_prediction,Y_train,average='weighted'))

print('Recall :',recall_score(X_train_prediction,Y_train,average='weighted'))

print('F1 score : ', f1_score(X_train_prediction,Y_train,average='weighted'))

# accuracy on test data
X_test_prediction = modelNB.predict(X_test)
test_data_accuracy = accuracy_score(X_test_prediction, Y_test)

print('Accuracy on Test data : ', test_data_accuracy)

print('Presion :',precision_score(X_test_prediction,Y_test,average='weighted'))
print('Recall :',recall_score(X_test_prediction,Y_test,average='weighted'))

print('F1 score : ', f1_score(X_test_prediction,Y_test,average='weighted'))

# confusion matrix
cm = confusion_matrix(Y_test, X_test_prediction)
print('Confusion Matrix : ')
print(cm)

Accuracy on Train data :  0.4310722100656455
Presion : 0.7353760190663968
Recall : 0.4310722100656455
F1 score :  0.529228148957348
Accuracy on Test data :  0.4005102040816326
Presion : 0.714845342747101
Recall : 0.4005102040816326
F1 score :  0.4925107240348368
Confusion Matrix : 
[[112   1   0]
 [ 91  38   0]
 [ 36 107   7]]
